'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const express=require('express');
const {MemorySessionStore}=require('../lib/account-sessions');const {csrfToken}=require('../lib/account-auth-http');const {MemoryReportStore}=require('../lib/report-store');const {installReportRoutes}=require('../lib/report-http');
const pepper=Buffer.alloc(32,7).toString('base64');
async function fixture(t,{guest=false}={}){const reporter={id:'p1',username:'alicia',security:{sessionVersion:1}};const target={id:'p2',username:'bruno',security:{sessionVersion:1}};const profiles={profiles:new Map([[reporter.id,reporter],[target.id,target]]),findByUsername:value=>[reporter,target].find(p=>p.username===String(value).toLowerCase())};const sessions=new MemorySessionStore({pepper});const issued=await sessions.issue({profileId:reporter.id,sessionVersion:1});const reports=new MemoryReportStore();const config={enabled:true,reportGuestEnabled:guest,appOrigin:'',sessionPepper:pepper,auditIpPepper:pepper};const evidence={messageId:'msg-1',authorProfileId:target.id,text:'mensaje denunciable',time:123};const app=express();installReportRoutes(app,{config,getProfiles:()=>profiles,getSessionStore:()=>sessions,getReportStore:()=>reports,findEvidence:(id,targetId)=>id===evidence.messageId&&targetId===target.id?evidence:null});const server=app.listen(0,'127.0.0.1');const origin=await new Promise(resolve=>server.once('listening',()=>resolve(`http://127.0.0.1:${server.address().port}`)));config.appOrigin=origin;t.after(()=>server.close());return{origin,reports,cookie:`mc_session=${issued.token}`,csrf:csrfToken(issued.session.id,pepper)};}
const body={reportedUsername:'bruno',category:'harassment',description:'Mensaje de acoso repetido dentro del chat',messageId:'msg-1'};
function post(f,overrides={},headers={}){return fetch(`${f.origin}/api/reports`,{method:'POST',headers:{origin:f.origin,'content-type':'application/json',...headers},body:JSON.stringify({...body,...overrides})});}
test('cuenta crea reporte y evidencia recuperada exclusivamente por servidor',async t=>{const f=await fixture(t);const response=await post(f,{}, {cookie:f.cookie,'x-csrf-token':f.csrf});assert.equal(response.status,201);const result=await response.json();const report=await f.reports.get(result.reportId);assert.equal(report.reporterProfileId,'p1');assert.equal(report.reporterDeviceHash,null);assert.deepEqual((await f.reports.evidenceFor(report.id))[0].snapshot,{messageId:'msg-1',authorProfileId:'p2',text:'mensaje denunciable',time:123});});
test('creación rechaza origen, CSRF y evidencia que no corresponde',async t=>{const f=await fixture(t);assert.equal((await post(f,{}, {origin:'https://evil.invalid',cookie:f.cookie,'x-csrf-token':f.csrf})).status,403);assert.equal((await post(f,{}, {cookie:f.cookie,'x-csrf-token':'incorrecto'})).status,403);assert.equal((await post(f,{messageId:'otro'}, {cookie:f.cookie,'x-csrf-token':f.csrf})).status,400);assert.equal(f.reports.reports.size,0);});
test('Mis reportes aísla al autor y omite evidencia y resolución interna',async t=>{const f=await fixture(t);await f.reports.create({reporterProfileId:'p1',reportedProfileId:'p2',category:'spam',description:'Publicidad repetida muchas veces en el chat'});await f.reports.create({reporterProfileId:'otro',reportedProfileId:'p2',category:'hate',description:'Contenido discriminatorio reiterado en el chat'});const response=await fetch(`${f.origin}/api/reports/mine`,{headers:{cookie:f.cookie}});assert.equal(response.status,200);assert.equal(response.headers.get('cache-control'),'no-store');const payload=await response.json();assert.equal(payload.reports.length,1);assert.deepEqual(Object.keys(payload.reports[0]).sort(),['category','createdAt','id','status','updatedAt']);});
test('invitado requiere flag, UUID y evidencia; persiste solo hash',async t=>{const disabled=await fixture(t);assert.equal((await post(disabled,{}, {'x-device-token':'123e4567-e89b-42d3-a456-426614174000'})).status,401);const f=await fixture(t,{guest:true});assert.equal((await post(f,{messageId:undefined},{'x-device-token':'123e4567-e89b-42d3-a456-426614174000'})).status,400);assert.equal((await post(f,{}, {'x-device-token':'arbitrario'})).status,401);const response=await post(f,{}, {'x-device-token':'123e4567-e89b-42d3-a456-426614174000'});assert.equal(response.status,201);const report=await f.reports.get((await response.json()).reportId);assert.equal(report.reporterProfileId,null);assert.match(report.reporterDeviceHash,/^[0-9a-f]{64}$/);assert.notEqual(report.reporterDeviceHash,'123e4567-e89b-42d3-a456-426614174000');});
test('límite antiabuso bloquea el cuarto reporte por cuenta',async t=>{const f=await fixture(t);for(let i=0;i<3;i++)assert.equal((await post(f,{}, {cookie:f.cookie,'x-csrf-token':f.csrf})).status,201);assert.equal((await post(f,{}, {cookie:f.cookie,'x-csrf-token':f.csrf})).status,429);});
